version: '3.3'
services:
    apache:
        image: 'php:8.0-apache'
        container_name: scaffolding-apache
        restart: always
        build:
            context: ./.devops/php
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - '9001:80'
        volumes:
            - .:/var/www/html/
            - ./.devops/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./.devops/apache/httpd.conf:/etc/apache2/conf-available/httpd.conf
            - ./.devops/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        networks:
          - scaffolding-apache
networks:
    scaffolding-apache:
        driver: bridge